# fly.toml app configuration file generated for koru-app on 2025-05-13T20:21:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'koru-app'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
