packages:
  - apps/*
  - packages/*
  - services/*
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
injectWorkspacePackages: true
nodeLinker: hoisted
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
